import type { Metadata } from 'next';
import Sidebar from './_components/Sidebar/Sidebar';
import MaxWidthWrapper from '@/components/MaxWidthWrapper/MaxWidthWrapper';
import Footer from '@/components/Footer/Footer';

export const metadata: Metadata = {
  title: 'Autobuy',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <MaxWidthWrapper>
        <div className="relative flex min-h-[90vh] w-full">
          <Sidebar />
          <div className="w-full     h-full">{children}</div>
        </div>
      </MaxWidthWrapper>
      <Footer />
    </>
  );
}
