import Navbar from '@/components/Navbar/Navbar';
import AppProvider from '@/context/AppContext';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();
  // const routes = ['/reset-password', '/forgot-password'];
  // const dashboardRoutes = ['/orders', '/messages', '/saved', '/settings'];
  // const shouldShow = routes.includes(pathname);
  return (
    <main>
      <Navbar />
      <main className="bg-[#f7f7f7]">
        <AppProvider>{children}</AppProvider>
      </main>
    </main>
  );
}
