'use client';
import Footer from '@/components/Footer/Footer';
import Navbar from '@/components/Navbar/Navbar';
// import type { Metadata } from 'next';
import { usePathname } from 'next/navigation';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const routes = ['/reset-password', '/forgot-password'];
  console.log(pathname);
  const shouldShow = routes.includes(pathname);
  console.log(shouldShow);
  return (
    <main>
      {!shouldShow && <Navbar />}
      <div>{children}</div>
      {!shouldShow && <Footer />}
    </main>
  );
}
