import Hero from '@/app/(buyer)/_components/Hero/Hero';
import VehicleTypeFilters from '../_components/Filters/VehicleTypeFilters';
import Topselling from '../_components/TopSelling/Topselling';
import Ourvalue from '../_components/Ourvalue/Ourvalue';
import PopularVehicle from '../_components/PopularVehicle/PopularVehicle';
import Footer from '@/components/Footer/Footer';
import HowitWorks from '../_components/HowitWorks/HowitWorks';
import SellNow from '../_components/SellNow/SellNow';

export const metadata = {
  title: 'Autobuy',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main className="w-full">
      <Hero />
      <VehicleTypeFilters />
      {/* <Stats /> */}
      <Topselling />
      <Ourvalue />
      <HowitWorks />
      <SellNow />
      <PopularVehicle />
      <Footer />
    </main>
  );
}
