import type { Metadata } from 'next';
import Sidebar from './_components/Sidebar';
import Navbar from '@/components/Navbar/SelllerNavbar';

export const metadata: Metadata = {
  title: 'Autobuy',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <main className="flex min-h-[90vh] w-full">
        <Sidebar />
        <div className="w-full h-full">{children}</div>
      </main>
    </>
  );
}
