import Footer from '@/components/Footer/Footer';
import Navbar from '@/components/Navbar/SelllerNavbar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <Navbar />
      <main className="min-h-screen">{children}</main>

      <main className="mt-8">
        <Footer bgColor="#F7F7F7" btnColor="bg-secondary-500" />
      </main>
    </main>
  );
}
