import React from 'react';
import Image from 'next/image';
import './page.css';

import MaxWidthWrapper from '@/components/MaxWidthWrapper/MaxWidthWrapper';
import SellerStep from '@/app/(seller)/_components/SellerStep/SellerStep';
import HeroImg from '@/app/(seller)/assets/sellerimg.svg';
import SVector from '@/app/(seller)/assets/seamlessvector.svg';
import Track from '@/app/(seller)/assets/track.svg';
import BgVector from '@/app/(seller)/assets/backgroundvector.svg';

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTriggerTwo,
} from '@/components/ui/accordion';
import ModalStepper from '../_components/ModalStepper';

export const metadata = {
  title: 'Autobuy',
  description: 'Generated by create next app',
};

const Seller = () => {
  return (
    <div>
      <section className="relative w-full h-full">
        <div className="grid w-full place-items-center h-auto md:h-[calc(100vh_-_76px)] md:max-h-[738px] bg-gradient-to-b from-[#FC816940] via-[#F199892D] t0-[#FFFFFF1A]">
          <MaxWidthWrapper>
            <div className="flex py-6 z-10 relative w-full gap-4 flex-col md:flex-row items-center justify-around">
              <div className="flex flex-col gap-6">
                <div className="flex justify-center md:justify-start ">
                  <Image src={HeroImg} alt="Image" height={150} width={150} />
                </div>
                <div className="max-w-[658px] text-black text-center md:text-start">
                  <h1 className="font-bold text-3xl md:text-[40px] lg:text-[54px] leading-[40px] md:leading-[70px]">
                    Experience a{' '}
                    <span className="px-3 md:px-[15px] relative inline-block">
                      seamless
                      <Image
                        src={SVector}
                        alt="vector"
                        width={275}
                        height={100}
                        className="absolute -top-[25%] md:-top-[4%] lg:-top-[22%] right-0 w-[98%] md:w-auto"
                      />
                    </span>{' '}
                    way to showcase and sell your car.
                  </h1>
                  <p className="min-[380px]:text-lg mt-2">
                    Where Your Vehicle Finds Its Next Adventure!
                  </p>
                </div>
              </div>

              <ModalStepper />
            </div>
          </MaxWidthWrapper>
        </div>
      </section>

      <SellerStep />

      <section className="my-24 relative ">
        <MaxWidthWrapper>
          <div className="text-center md:text-start w-full md:w-[70%] mb-12">
            <h1 className="font-bold text-3xl md:text-[42px] md:leading-[52px] text-[#1A1A1A] mb-2">
              You don’t just sell, we help you track and manage every sale in one place!
            </h1>
            <p className="text-sm md:text-base">
              Lorem ipsum dolor sit amet consectetur. Sagittis ac nibh faucibus turpis adipiscing
              ultricies massa. Gravida viverra nibh bibendum tortor. Non elementum ipsum etiam
              laoreet ultricies eget.
            </p>
          </div>
          <div className="flex">
            <div>
              <Image src={Track} alt="track" width={713} height={360} />
            </div>
            <div></div>
          </div>
        </MaxWidthWrapper>
        <Image
          src={BgVector}
          alt="background vector"
          height={1000}
          width={500}
          className="absolute -top-[40%] right-0 -z-10 hidden sm:block"
        />
      </section>

      <section className="bg-[#FFF6F0] py-10">
        <MaxWidthWrapper>
          <h1 className=" font-bold text-2xl text-center md:text-left mb-3  md:text-[42px] mt-8">
            What Our Customers Are Saying
          </h1>
          <p className="font-medium text-center md:text-left">
            Weve sold more than 200 cars for customers and received a lot of great feedback. See
            what our clients say about us.
          </p>
          <div className="flex w-full overflow-y-auto gap-4 ">
            {[1, 2, 3, 4, 5, 6, 7].map((item) => (
              <div key={item} className="min-w-[400px] bg-white shadow-sm px-6 py-8 my-8 space-y-4">
                <div className="flex items-center justify-start gap-2">
                  <div>
                    <p className="font-bold">Name</p>
                    <p className="text-neutral-500">Date of commet</p>
                  </div>
                </div>

                <p>
                  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione expedita
                  reiciendis dicta id? Est sapiente nisi sit enim atque optio vero iste quo, sed
                  consequuntur laudantium unde amet delectus alias? Cum illo id nemo aut natus
                </p>
              </div>
            ))}
          </div>
          <p className="underline text-secondary-700 text-lg cursor-pointer mt-3">
            See All Reviews
          </p>
        </MaxWidthWrapper>
      </section>

      <section className=" mt-16">
        <MaxWidthWrapper>
          <div className="flex flex-col md:flex-row gap-6 md:gap-16">
            <div className="flex justify-center">
              <div className="text-center md:text-start max-w-[600px]">
                <h1 className=" font-bold text-3xl md:text-[42px] md:leading-[50px] mb-3">
                  Frequently Asked Questions
                </h1>
                <p className="font-medium mb-6">Have questions? Were here to help</p>
                <button
                  type="button"
                  className="text-secondary-700 font-medium border border-secondary-700 rounded-[50px] px-4 py-3 w-[186px]"
                >
                  View All FAQs
                </button>
              </div>
            </div>

            <div className="mb-16 w-full">
              <Accordion type="single" collapsible className="w-full">
                <AccordionItem value="item-1" className="border-secondary-500">
                  <AccordionTriggerTwo className="hover:no-underline text-left md:text-center">
                    How does the car inspection process work?
                  </AccordionTriggerTwo>
                  <AccordionContent className="w-full">
                    Lorem ipsum dolor sit amet consectetur. Nisl mi phasellus scelerisque nullam.
                    Nunc erat viverra pellentesque ac ullamcorper ultrices vel vehicula lobortis. Ac
                    risus dui lectus porta vestibulum odio massa. Feugiat est lobortis non justo et
                    iaculis integer faucibus sed.
                  </AccordionContent>
                </AccordionItem>

                <AccordionItem className="border-secondary-500" value="item-2">
                  <AccordionTriggerTwo className="hover:no-underline text-left md:text-center">
                    How long does the inspection take?
                  </AccordionTriggerTwo>
                  <AccordionContent>
                    Lorem ipsum dolor sit amet consectetur. Nisl mi phasellus scelerisque nullam.
                    Nunc erat viverra pellentesque ac ullamcorper ultrices vel vehicula lobortis. Ac
                    risus dui lectus porta vestibulum odio massa. Feugiat est lobortis non justo et
                    iaculis integer faucibus sed.
                  </AccordionContent>
                </AccordionItem>

                <AccordionItem className="border-secondary-500" value="item-3">
                  <AccordionTriggerTwo className="hover:no-underline text-left md:text-center">
                    Can I sell my car without an inspection?
                  </AccordionTriggerTwo>
                  <AccordionContent>
                    Lorem ipsum dolor sit amet consectetur. Nisl mi phasellus scelerisque nullam.
                    Nunc erat viverra pellentesque ac ullamcorper ultrices vel vehicula lobortis. Ac
                    risus dui lectus porta vestibulum odio massa. Feugiat est lobortis non justo et
                    iaculis integer faucibus sed.
                  </AccordionContent>
                </AccordionItem>

                <AccordionItem className="border-secondary-500" value="item-4">
                  <AccordionTriggerTwo className="hover:no-underline text-left md:text-center">
                    How does the AI-generated vehicle appraisal work?
                  </AccordionTriggerTwo>
                  <AccordionContent>
                    Lorem ipsum dolor sit amet consectetur. Nisl mi phasellus scelerisque nullam.
                    Nunc erat viverra pellentesque ac ullamcorper ultrices vel vehicula lobortis. Ac
                    risus dui lectus porta vestibulum odio massa. Feugiat est lobortis non justo et
                    iaculis integer faucibus sed.
                  </AccordionContent>
                </AccordionItem>

                <AccordionItem className="border-secondary-500" value="item-5">
                  <AccordionTriggerTwo className="hover:no-underline text-left md:text-center">
                    What do I need to bring to the inspection appointment?
                  </AccordionTriggerTwo>
                  <AccordionContent>
                    Lorem ipsum dolor sit amet consectetur. Nisl mi phasellus scelerisque nullam.
                    Nunc erat viverra pellentesque ac ullamcorper ultrices vel vehicula lobortis. Ac
                    risus dui lectus porta vestibulum odio massa. Feugiat est lobortis non justo et
                    iaculis integer faucibus sed.
                  </AccordionContent>
                </AccordionItem>
              </Accordion>
            </div>
          </div>
        </MaxWidthWrapper>
      </section>
    </div>
  );
};

export default Seller;
