import React from 'react';
import Image from 'next/image';
import './page.css';

import MaxWidthWrapper from '@/components/MaxWidthWrapper/MaxWidthWrapper';
import SellerStep from '@/app/(seller)/_components/SellerStep/SellerStep';
import RegistrationProcess from '@/app/(seller)/assets/registrationprocess.svg';
import InspectionProcess from '@/app/(seller)/assets/inspectionprocess.svg';
import SalesProcess from '@/app/(seller)/assets/salesprocess.svg';

import VehicleEvaluation from '../_components/VehicleEvaluation';

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';

export const metadata = {
  title: 'Autobuy',
  description: 'Generated by create next app',
};

const Seller = () => {
  return (
    <div>
      <section className="relative w-full h-full">
        <div className="seller-bcg grid w-full place-items-center h-[calc(100vh_-_76px)] bg-black/45">
          <div className="absolute top-0  left-0 w-full h-full bg-black bg-opacity-45"></div>

          <MaxWidthWrapper>
            <div className="flex z-10 relative w-full gap-4 md:gap-0 flex-col md:flex-row items-center justify-between">
              <div className="max-w-[666px] text-center md:text-left">
                <h1 className="font-bold text-white  min-[380px]:text-[30px]  lg:text-[60px]">
                  Experience <span className="text-secondary-500"> Seamless</span> and
                  <span className="text-secondary-500">Effortless</span> Transitions
                </h1>
                <p className="text-white md:max-w-[380px] text-sm min-[380px]:text-xl font-medium">
                  Where Your Vehicle Finds Its Next Adventure!
                </p>
              </div>

              <div className="">
                <VehicleEvaluation />
              </div>
            </div>
          </MaxWidthWrapper>
        </div>
      </section>

      <SellerStep />

      <section className="mt-20 max-w-5xl mx-auto px-14  flex items-center justify-center">
        <div>
          <div className="text-center">
            <h1 className="text-2xl md:text-3xl font-bold">How it works?</h1>
            <p className="md:text-lg">
              Transform your vehicle into cash with our seamless selling process!
            </p>
          </div>

          <div className=" mt-5 grid grid-cols-1 md:grid-cols-2 space-y-4 md:space-y-0 md:space-x-4 place-items-center">
            <div className=" flex items-center justify-center">
              <Image src={RegistrationProcess} alt="Registraiton Process" />
            </div>

            <div className=" space-y-2  ">
              <h1 className="text-xl md:test-2xl font-bold my-2 w-full">Registration Process</h1>
              <p className="text-sm w-full ">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde cumque asperiores
                reiciendis corrupti aliquam vitae iusto recusandae non expedita omnis.
              </p>
            </div>
          </div>

          <div className=" mt-5 grid grid-cols-1 md:grid-cols-2 space-y-4 md:space-y-0 md:space-x-4 place-items-center">
            <div className=" space-y-2 max-w-[616px] order-2 md:order-1">
              <h1 className="text-xl md:test-2xl font-bold my-2 w-full">Our Inspection Process</h1>
              <p className="text-sm w-full ">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde cumque asperiores
                reiciendis corrupti aliquam vitae iusto recusandae non expedita omnis.
              </p>
              <p className="text-sm w-full">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates sit cumque
                consequatur magnam eius ut quo distinctio architecto alias earum!
              </p>
            </div>
            <div className=" flex items-center justify-center order-1 md:order-2">
              <Image src={InspectionProcess} alt="Registraiton Process" className="w-full " />
            </div>
          </div>

          <div className=" mt-5 grid grid-cols-1 md:grid-cols-2 space-y-4 md:space-y-0 md:space-x-4 place-items-center">
            <div className=" flex items-center justify-center">
              <Image src={SalesProcess} alt="Registraiton Process" />
            </div>
            <div className=" space-y-2 max-w-[616px] ">
              <h1 className="text-xl md:test-2xl font-bold my-2 w-full">Our sales Process</h1>
              <p className="text-sm w-full ">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam sapiente, libero
                consectetur sit corrupti placeat iste cumque tempore laboriosam esse sequi aperiam,
                quod optio fuga. Numquam itaque dicta ad, provident ea fuga nam ab neque consequatur
                quos. Soluta, dignissimos dicta.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="bg-[#FFF6F0] py-10">
        <MaxWidthWrapper>
          <h1 className=" font-bold text-2xl text-center md:text-left mb-3  md:text-[42px] mt-8">
            What Our Customers Are Saying
          </h1>
          <p className="font-medium text-center md:text-left">
            Weve sold more than 200 cars for customers and received a lot of great feedback. See
            what our clients say about us.
          </p>
          <div className="flex w-full overflow-y-auto gap-4 ">
            {[1, 2, 3, 4, 5, 6, 7].map((item) => (
              <div key={item} className="min-w-[400px] bg-white shadow-sm px-6 py-8 my-8 space-y-4">
                <div className="flex items-center justify-start gap-2">
                  <div>
                    <p className="font-bold">Name</p>
                    <p className="text-neutral-500">Date of commet</p>
                  </div>
                </div>

                <p>
                  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione expedita
                  reiciendis dicta id? Est sapiente nisi sit enim atque optio vero iste quo, sed
                  consequuntur laudantium unde amet delectus alias? Cum illo id nemo aut natus
                </p>
              </div>
            ))}
          </div>
        </MaxWidthWrapper>
      </section>

      <section className=" mt-16">
        <MaxWidthWrapper>
          <div className="text-center">
            <h1 className=" font-bold text-2xl  md:text-[42px] mt-8 mb-3">
              Frequently Asked Questions
            </h1>
            <p className="font-medium">Have questions? Were here to help</p>
          </div>

          <div className=" my-16">
            <Accordion type="single" collapsible className="w-full">
              <AccordionItem value="item-1" className="border-secondary-500">
                <AccordionTrigger className="hover:no-underline text-left md:text-center">
                  How does the car inspection process work?
                </AccordionTrigger>
                <AccordionContent className="w-full">
                  Lorem ipsum dolor sit amet consectetur. Nisl mi phasellus scelerisque nullam. Nunc
                  erat viverra pellentesque ac ullamcorper ultrices vel vehicula lobortis. Ac risus
                  dui lectus porta vestibulum odio massa. Feugiat est lobortis non justo et iaculis
                  integer faucibus sed.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem className="border-secondary-500" value="item-2">
                <AccordionTrigger className="hover:no-underline text-left md:text-center">
                  How long does the inspection take?
                </AccordionTrigger>
                <AccordionContent>
                  Lorem ipsum dolor sit amet consectetur. Nisl mi phasellus scelerisque nullam. Nunc
                  erat viverra pellentesque ac ullamcorper ultrices vel vehicula lobortis. Ac risus
                  dui lectus porta vestibulum odio massa. Feugiat est lobortis non justo et iaculis
                  integer faucibus sed.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem className="border-secondary-500" value="item-3">
                <AccordionTrigger className="hover:no-underline text-left md:text-center">
                  Can I sell my car without an inspection?
                </AccordionTrigger>
                <AccordionContent>
                  Lorem ipsum dolor sit amet consectetur. Nisl mi phasellus scelerisque nullam. Nunc
                  erat viverra pellentesque ac ullamcorper ultrices vel vehicula lobortis. Ac risus
                  dui lectus porta vestibulum odio massa. Feugiat est lobortis non justo et iaculis
                  integer faucibus sed.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem className="border-secondary-500" value="item-4">
                <AccordionTrigger className="hover:no-underline text-left md:text-center">
                  How does the AI-generated vehicle appraisal work?
                </AccordionTrigger>
                <AccordionContent>
                  Lorem ipsum dolor sit amet consectetur. Nisl mi phasellus scelerisque nullam. Nunc
                  erat viverra pellentesque ac ullamcorper ultrices vel vehicula lobortis. Ac risus
                  dui lectus porta vestibulum odio massa. Feugiat est lobortis non justo et iaculis
                  integer faucibus sed.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem className="border-secondary-500" value="item-5">
                <AccordionTrigger className="hover:no-underline text-left md:text-center">
                  What do I need to bring to the inspection appointment?
                </AccordionTrigger>
                <AccordionContent>
                  Lorem ipsum dolor sit amet consectetur. Nisl mi phasellus scelerisque nullam. Nunc
                  erat viverra pellentesque ac ullamcorper ultrices vel vehicula lobortis. Ac risus
                  dui lectus porta vestibulum odio massa. Feugiat est lobortis non justo et iaculis
                  integer faucibus sed.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </div>
        </MaxWidthWrapper>
      </section>
    </div>
  );
};

export default Seller;
