import Navbar from '@/components/Navbar/SelllerNavbar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <Navbar />
      <div className="min-h-screen">{children}</div>
      {/* <Footer /> */}
    </main>
  );
}
