import React from 'react';
import Image from 'next/image';
import './page.css';

import MaxWidthWrapper from '@/components/MaxWidthWrapper/MaxWidthWrapper';
import Sell from '@/app/(seller)/assets/sell.svg';
import SellerStep from '@/app/(seller)/_components/SellerStep/SellerStep';
import RegistrationProcess from '@/app/(seller)/assets/registrationprocess.svg';
import InspectionProcess from '@/app/(seller)/assets/inspectionprocess.svg';
import SalesProcess from '@/app/(seller)/assets/salesprocess.svg';
import NextStep from '@/app/(seller)/assets/nextstep.svg';
import Next from '@/app/(seller)/assets/next.svg';
// import Review from '@/app/(seller)/assets/topreview.svg';

export const metadata = {
  title: 'Autobuy',
  description: 'Generated by create next app',
};

const Seller = () => {
  return (
    <main>
      <section className="relative w-full h-full">
        <div className="seller-bcg grid place-items-center h-[calc(100vh_-_76px)] bg-black/45">
          <div className="absolute top-0 left-0 w-full h-full bg-black bg-opacity-45"></div>

          <div className=" h-full flex flex-col items-center justify-center z-10 space-y-2">
            <h1 className="text-xl  text-white sm:text-3xl font-bold md:text-[40px]">
              Unlock EffortlessTransitions
            </h1>
            <p className="  text-white text-lg max-w-[300px] sm:text-xl text-center font-semibold">
              Where Your Vehicle Finds Its Next Adventure
            </p>
            <button className="text-white rounded-[4px] md:w-[320px] space-x-4 bg-secondary-500 px-4 py-2 flex items-center justify-center">
              <Image src={Sell} alt="Sell" />
              <span>Sell</span>
            </button>
          </div>
        </div>
      </section>

      <SellerStep />

      <section className="mt-8 max-w-5xl mx-auto px-6">
        <div className="text-center">
          <h1 className="text-2xl md:text-3xl font-bold">How it works?</h1>
          <p className="md:text-lg">
            Transform your vehicle into cash with our seamless selling process!
          </p>
        </div>

        <div className=" mt-5 grid grid-cols-1 md:grid-cols-3 space-y-4 md:space-y-0 md:space-x-4">
          <div className="col-span-2 space-y-2 max-w-[616px] ">
            <h1 className="text-xl md:test-2xl font-bold my-2 w-full">Registration Process</h1>
            <p className="text-sm w-full ">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde cumque asperiores
              reiciendis corrupti aliquam vitae iusto recusandae non expedita omnis.
            </p>
            <p className="text-sm w-full">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates sit cumque
              consequatur magnam eius ut quo distinctio architecto alias earum!
            </p>
          </div>

          <div className="col-span- flex items-center justify-center">
            <Image src={RegistrationProcess} alt="Registraiton Process" />
            <Image src={NextStep} alt="Next Step" className="hidden xl:block" />
          </div>
        </div>

        <div className=" mt-5 grid grid-cols-1 md:grid-cols-3 space-y-4 md:space-y-0 md:space-x-4">
          <div className="col-span- flex items-center justify-center">
            <Image src={Next} alt="Next Step" className="hidden xl:block -ml-28 " />
            <Image src={InspectionProcess} alt="Registraiton Process" className="w-full " />
          </div>

          <div className="col-span-2 space-y-2 max-w-[616px]">
            <h1 className="text-xl md:test-2xl font-bold my-2 w-full">Our Inspection Process</h1>
            <p className="text-sm w-full ">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde cumque asperiores
              reiciendis corrupti aliquam vitae iusto recusandae non expedita omnis.
            </p>
            <p className="text-sm w-full">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates sit cumque
              consequatur magnam eius ut quo distinctio architecto alias earum!
            </p>
          </div>
        </div>

        <div className=" mt-5 grid grid-cols-1 md:grid-cols-3 space-y-4 md:space-y-0 md:space-x-4">
          <div className="col-span-2 space-y-2 max-w-[616px] ">
            <h1 className="text-xl md:test-2xl font-bold my-2 w-full">Our sales Process</h1>
            <p className="text-sm w-full ">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam sapiente, libero
              consectetur sit corrupti placeat iste cumque tempore laboriosam esse sequi aperiam,
              quod optio fuga. Numquam itaque dicta ad, provident ea fuga nam ab neque consequatur
              quos. Soluta, dignissimos dicta.
            </p>
            <p className="text-sm w-full">Lorem ipsum dolor</p>
            <p className="text-sm w-full">Lorem ipsum dolor</p>
            <p className="text-sm w-full">Lorem ipsum dolor</p>
            <p className="text-sm w-full">Lorem ipsum dolor</p>
          </div>

          <div className="col-span- flex items-center justify-center">
            {/* <Image src={NextStep} alt="Next Step" className="hidden xl:block" /> */}
            <Image src={SalesProcess} alt="Registraiton Process" />
          </div>
        </div>
      </section>

      <MaxWidthWrapper>
        <h1 className="text-center font-bold text-2xl mt-8">Top Reviews</h1>
        <div className="flex w-full overflow-y-auto gap-4 ">
          {[1, 2, 3, 4, 5, 6, 7].map((item) => (
            <div key={item} className="min-w-[400px] shadow-sm p-4 space-y-4">
              <div className="flex items-center justify-start gap-2">
                <Image src={''} alt="Avatar" className="w-16 h-16 rounded-full bg-zinc-400" />
                <div>
                  <p>name</p>
                  <p>Date of commet</p>
                </div>
              </div>

              <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione expedita
                reiciendis dicta id? Est sapiente nisi sit enim atque optio vero iste quo, sed
                consequuntur laudantium unde amet delectus alias? Cum illo id nemo aut natus maxime
                voluptas maiores! Omnis illum beatae voluptatem rem laboriosam natus ab deleniti
                nisi id.
              </p>
            </div>
          ))}
        </div>
      </MaxWidthWrapper>

      <section></section>
    </main>
  );
};

export default Seller;
